CREATE TABLE app_users (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name VARCHAR(100) NOT NULL,
 email VARCHAR(254) NOT NULL UNIQUE,
 password_hash VARCHAR(100) NOT NULL,
 role VARCHAR(20) NOT NULL CHECK (role IN ('ADOTANTE','RESPONSAVEL'))
);
CREATE TABLE animals (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 owner_id BIGINT NOT NULL REFERENCES app_users(id),
 name VARCHAR(80) NOT NULL,
 species VARCHAR(10) NOT NULL CHECK (species IN ('CAO','GATO')),
 size VARCHAR(10) NOT NULL CHECK (size IN ('PEQUENO','MEDIO','GRANDE')),
 age_months INTEGER NOT NULL CHECK (age_months >= 0 AND age_months <= 480),
 city VARCHAR(100) NOT NULL,
 description VARCHAR(3000) NOT NULL,
 care VARCHAR(2000) NOT NULL,
 photo_url VARCHAR(1000) NOT NULL,
 vaccinated BOOLEAN NOT NULL,
 neutered BOOLEAN NOT NULL,
 status VARCHAR(20) NOT NULL CHECK (status IN ('DISPONIVEL','EM_PROCESSO','ADOTADO'))
);
CREATE TABLE adoption_requests (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 animal_id BIGINT NOT NULL REFERENCES animals(id),
 adopter_id BIGINT NOT NULL REFERENCES app_users(id),
 housing VARCHAR(1000) NOT NULL,
 routine VARCHAR(2000) NOT NULL,
 experience VARCHAR(2000) NOT NULL,
 commitment BOOLEAN NOT NULL CHECK (commitment = TRUE),
 status VARCHAR(20) NOT NULL CHECK (status IN ('PENDENTE','APROVADA','RECUSADA','CANCELADA','CONCLUIDA')),
 decision_note VARCHAR(1000) NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_animals_owner ON animals(owner_id);
CREATE INDEX idx_requests_animal ON adoption_requests(animal_id);
CREATE INDEX idx_requests_adopter ON adoption_requests(adopter_id);
